# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: vitos
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: indra-challenge
# "service" is the name of this project. This will also be added to your AWS resource names.
service: indra-challenge

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x

functions:
  hello:
    handler: src/handler.hello
    events:
      - httpApi:
          path: /
          method: get
